from typing import Any, Protocol

from app.core.security import AuthenticatedUser
from app.domain.pending.entities import PendingActionData


class PendingActionRepository(Protocol):
    def get_session_owner(self, session_id: str) -> int | None: ...
    def get_pending(self, session_id: str, *, for_update: bool = False) -> PendingActionData | None: ...
    def add_pending(self, action: PendingActionData) -> PendingActionData: ...
    def delete_pending(self, action_id: int) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class PendingActionHandler(Protocol):
    def validate_arguments(self, arguments: dict[str, Any]) -> dict[str, Any]: ...
    def execute(self, actor: AuthenticatedUser, arguments: dict[str, Any]) -> Any: ...

