from datetime import date
from decimal import Decimal
from typing import Protocol

from app.domain.leave.entities import LeaveBalanceSnapshot, LeaveRequestData, LeaveType


class LeaveRepository(Protocol):
    def get_balances(self, employee_id: int, leave_type: LeaveType | None = None,
                     *, for_update: bool = False) -> list[LeaveBalanceSnapshot]: ...
    def get_holidays(self, start_date: date, end_date: date) -> set[date]: ...
    def get_pending_days(self, employee_id: int, leave_type: LeaveType) -> Decimal: ...
    def has_overlapping_request(self, employee_id: int, start_date: date, end_date: date) -> bool: ...
    def add_request(self, request: LeaveRequestData) -> LeaveRequestData: ...
    def list_requests(self, employee_id: int) -> list[LeaveRequestData]: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

