from datetime import date
from decimal import Decimal
from typing import Protocol

from app.domain.leave.entities import (
    LeaveBalanceSnapshot,
    LeaveRequestData,
    LeaveRequestEventData,
    LeaveStatus,
    LeaveType,
)


class LeaveRepository(Protocol):
    def get_balances(self, employee_id: int, leave_type: LeaveType | None = None,
                     *, for_update: bool = False) -> list[LeaveBalanceSnapshot]: ...
    def get_holidays(self, start_date: date, end_date: date) -> set[date]: ...
    def get_pending_days(self, employee_id: int, leave_type: LeaveType) -> Decimal: ...
    def has_overlapping_request(self, employee_id: int, start_date: date, end_date: date) -> bool: ...
    def add_request(self, request: LeaveRequestData) -> LeaveRequestData: ...
    def list_requests(self, employee_id: int) -> list[LeaveRequestData]: ...
    def get_request(self, request_id: int, *, for_update: bool = False) -> LeaveRequestData | None: ...
    def list_managed_requests(
        self, manager_employee_id: int | None, status: LeaveStatus | None = None
    ) -> list[LeaveRequestData]: ...
    def increase_used_days(self, employee_id: int, leave_type: LeaveType, days: Decimal) -> None: ...
    def update_request_status(
        self, request_id: int, status: LeaveStatus, actor_user_id: int, comment: str | None
    ) -> LeaveRequestData: ...
    def add_event(self, event: LeaveRequestEventData) -> LeaveRequestEventData: ...
    def list_events(self, request_id: int) -> list[LeaveRequestEventData]: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
