from typing import Protocol

from app.rag.models import PolicyChunk, PolicySearchResult


class EmbeddingProvider(Protocol):
    def embed_documents(self, texts: list[str]) -> list[list[float]]: ...
    def embed_query(self, text: str) -> list[float]: ...


class PolicyVectorStore(Protocol):
    def ensure_collection(self) -> None: ...
    def replace_document(self, document: str, chunks: list[PolicyChunk], vectors: list[list[float]]) -> None: ...
    def search(self, vector: list[float], *, top_k: int, score_threshold: float) -> list[PolicySearchResult]: ...

